language: node_js
node_js:
  - "node"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
os:
  - linux
  - osx
osx_image: xcode7.3
matrix:
  fast_finish: true
before_install:
  - npm install -g npm
  - npm config set spin false
script: npm run travis
addons:
  code_climate:
    repo_token: d3494c5bb5f3df7d98635dbc2aa962c7ce5e14c61f574a8c7304dfa9bc8783e4
after_success:
  - cat coverage/lcov.info | node_modules/.bin/coveralls --verbose
  - codeclimate-test-reporter < coverage/lcov.info
