language: node_js
node_js:
- stable
- 8
- 6
- 10
osx_image: xcode7.3
matrix:
  fast_finish: true
install: yarn --ignore-engines
script: yarn run travis
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script: npx semantic-release@15
addons:
  code_climate:
    repo_token: d3494c5bb5f3df7d98635dbc2aa962c7ce5e14c61f574a8c7304dfa9bc8783e4
cache: yarn
after_success:
- cat coverage/lcov.info | node_modules/.bin/coveralls --verbose
- codeclimate-test-reporter < coverage/lcov.info
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
  except:
  - /^v\d+\.\d+\.\d+$/
env:
  global:
  - GK_LOCK_YARN_OPTS="--ignore-engines"
