name: Prepare CI cache

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  prepare-yarn-cache:
    name: Prepare yarn cache for ${{ inputs.os }}
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: yarn

      - name: Validate cache
        run: yarn --frozen-lockfile
